server:
  port: 8185
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lhf_springboot2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
